<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\User;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class AuthController extends AbstractController
{
   public function register(Request $request, UserPasswordEncoderInterface $encoder)
   {
       $em = $this->getDoctrine()->getManager();

       $username = json_decode($request->getContent())->username;
       $password = json_decode($request->getContent())->password;
       $email = json_decode($request->getContent())->email;
       $nom = json_decode($request->getContent())->nom;
       $prenom = json_decode($request->getContent())->prenom;
       $numTel = json_decode($request->getContent())->numTel;
       $numeroSiret = json_decode($request->getContent())->numeroSiret;
       $roles = json_decode($request->getContent())->roles;


       $user = new User();
       $user->setUsername($username);
       $user->setPassword($encoder->encodePassword($user, $password));
       $user->setRoles([$roles]);
       $user->setEmail($email);
       $user->setNom($nom);
       $user->setPrenom($prenom);
       $user->setNumTel($numTel);
       $user->setNumeroSiret($numeroSiret);

       $em->persist($user);
       $em->flush();

       return new Response(sprintf('User %s successfully created', $user->getUsername()));
   }

   public function api()
   {
       return new Response(sprintf('Logged in as %s', $this->getUser()->getUsername()));
   }

    public function getCompleteUser()
    {
        return $this->json(parent::getUser()); // TODO: Change the autogenerated stub
    }
}

